---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pv-claim
  labels:
    app: mongodb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  strategy:
    type: RollingUpdate
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 120
      maxSurge: "20%"
      maxUnavailable: "10%"
      pre: {}
      post: {}
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - image: registry.access.redhat.com/rhscl/mongodb-26-rhel7:latest
        imagePullPolicy: Always
        name: mongodb
        ports:
        - containerPort: 27017
          name: db-port
        env:
          - name: "MONGODB_USER"
            value: "mongodbuser"
          - name: "MONGODB_PASSWORD"
            value: "mongodbpassword"
          - name: "MONGODB_DATABASE"
            value: "sampledb"
          - name: "MONGODB_ADMIN_PASSWORD"
            value: "mongodbpassword"
        volumeMounts:
        - name: mongodb-data
          mountPath: /var/lib/mongodb/data
      volumes:
      - name: mongodb-data
        persistentVolumeClaim:
          claimName: mongodb-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: db-port
  labels:
    app: mongodb
spec:
  ports:
    - port: 27017
      name: db-port
      protocol: TCP
      targetPort: 27017
  selector:
    app: mongodb

